### ISSUE TITLE
Android13（一加9R）  app分身打开崩溃

### ISSUE THREAD

**Issue by Cleverlove7** [FSpaceCore/SpaceCore#31]
报错内容在aar中，无法更深入研究

报错日志：JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
    java.lang.AbstractMethodError: abstract method "void android.app.IServiceConnection.connected(android.content.ComponentName, android.os.IBinder, boolean)"
        at android.app.IServiceConnection$Stub.onTransact(IServiceConnection.java:91)
        at android.os.Binder.execTransactInternal(Binder.java:1331)
        at android.os.Binder.execTransact(Binder.java:1268)

FATAL EXCEPTION: binder:26022_5
    Process: space.dualmeta32:system_process, PID: 26022
    java.lang.AbstractMethodError: abstract method "void android.app.IServiceConnection.connected(android.content.ComponentName, android.os.IBinder, boolean)"
        at android.app.IServiceConnection$Stub.onTransact(IServiceConnection.java:91)
        at android.os.Binder.execTransactInternal(Binder.java:1331)
        at android.os.Binder.execTransact(Binder.java:1268)

**Comment by FSpaceCore** [comment]
你加一下telegram发个消息，我给你测试包试试。

**Comment by FSpaceCore** [comment]
已修复：https://github.com/FSpaceCore/SpaceCore/releases/tag/v3
