### ISSUE TITLE
tiktok从apk安装包加载方式会卡死

### ISSUE THREAD

**Issue by LuoYaoSheng** [FSpaceCore/SpaceCore#51]
Tiktok通过文件方式安装，可以正常打开。但当Tiktok从后台退出，再次打开就会一直卡屏，直到崩溃。

报错日志：
`2023-07-11 14:07:40.187 26863-26892 Parcel                        E  Reading a NULL string not supported here.
2023-07-11 14:07:40.189 26863-26879 DatabaseUtils            E  Writing exception to parcel
                                                                                                    java.lang.SecurityException: Calling uid: 10001 doesn't match source uid: 10449
                                                                                                    	at android.content.AttributionSource.enforceCallingUid(AttributionSource.java:250)
                                                                                                    	at android.content.AttributionSource.enforceCallingUidAndPid(AttributionSource.java:236)
                                                                                                    	at android.content.AttributionSource.<init>(AttributionSource.java:158)
                                                                                                    	at android.content.AttributionSource$1.createFromParcel(AttributionSource.java:492)
                                                                                                    	at android.content.AttributionSource$1.createFromParcel(AttributionSource.java:484)
                                                                                                    	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:289)
                                                                                                    	at android.os.Binder.transact(Binder.java:1084)
                                                                                                    	at z1.onTransact(:4)
                                                                                                    	at x2.onTransact(:10)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1221)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1163)`

**Comment by FSpaceCore** [comment]
这个问题将在下个版本修复

**Comment by dujianchi** [comment]
遇到了相同bug
```
Writing exception to parcel
java.lang.SecurityException: Calling uid: 10001 doesn't match sourceuid: 10234
	at android.content.AttributionSource.enforceCallingUid(AttributionSource.java:283)
	at android.content.AttributionSource.enforceCallingUidAndPid(AttributionSource.java:269)
	at android.content.AttributionSource.<init>(AttributionSource.java:159)
	at android.content.AttributionSource$1.createFromParcel(AttributionSource.java:525)
	at android.content.AttributionSource$1.createFromParcel(AttributionSource.java:517)
	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:289)
	at android.os.Binder.transact(Binder.java:1169)
	at z1.onTransact(:4)
	at x2.onTransact(:10)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1249)
```

跪求大佬快点解决
