### ISSUE TITLE
Demo apk 加载运行Messenger崩溃

### ISSUE THREAD

**Issue by paolo856** [FSpaceCore/SpaceCore#59]
加载运行Messenger报NullPointerException异常，麻烦帮看下是什么原因？
机型：huawei p30 
系统版本：Android9.0
报错日志如下：
16:21:07.825 20622-21085/com.facebook.orca E/AndroidRuntime: FATAL EXCEPTION: BgHandler
    Process: com.facebook.orca, PID: 20622
    java.lang.NullPointerException: java.lang.NullPointerException
        at |lyra|{/data/data/space.dualmeta64/fv/data/user/0/com.facebook.orca/lib-compressed/libdexload.so}._ZN8facebook3jni21throwNewJavaExceptionEP11_jthrowable(D6E543BF-44A2-F71B-493C-8D9E9393012C:611652)
        at |lyra|{/data/data/space.dualmeta64/fv/data/user/0/com.facebook.orca/lib-compressed/libdexload.so}._ZN8facebook3jni21throwNewJavaExceptionEPKcS2_(D6E543BF-44A2-F71B-493C-8D9E9393012C:460828)
        at |lyra|{/data/data/space.dualmeta64/fv/data/user/0/com.facebook.orca/lib-compressed/libdexload.so}._ZNK8facebook3jni6detail16HybridDestructor16getNativePointerEv(D6E543BF-44A2-F71B-493C-8D9E9393012C:468220)
        at |lyra|{/data/data/space.dualmeta64/fv/data/user/0/com.facebook.orca/lib-compressed/libcoldstart.so}.(0C86326A-CB5A-12DA-45C3-C5C15700AB4D:3623344)
        at |lyra|{/data/data/space.dualmeta64/fv/data/user/0/com.facebook.orca/lib-compressed/libcoldstart.so}.(0C86326A-CB5A-12DA-45C3-C5C15700AB4D:4633672)
        at |lyra|{/system/lib64/libart.so}.(40255FA0-FC4E-1935-A58C-D2BFA3441066:5574628)
        at |lyra|{/system/lib64/libart.so}.(40255FA0-FC4E-1935-A58C-D2BFA3441066:5537676)
        at |lyra|{/system/lib64/libart.so}._ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc(40255FA0-FC4E-1935-A58C-D2BFA3441066:709128)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPNS_11ShadowFrameEtPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2477996)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2453428)
        at |lyra|{/system/lib64/libart.so}.MterpInvokeDirect(40255FA0-FC4E-1935-A58C-D2BFA3441066:5344732)
        at |lyra|{/system/lib64/libart.so}.ExecuteMterpImpl(40255FA0-FC4E-1935-A58C-D2BFA3441066:5482264)
        at |lyra|{/system/lib64/libart.so}.(40255FA0-FC4E-1935-A58C-D2BFA3441066:2297016)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadERKNS_20CodeItemDataAccessorEPNS_11ShadowFrameEPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2320300)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2453400)
        at |lyra|{/system/lib64/libart.so}.MterpInvokeVirtual(40255FA0-FC4E-1935-A58C-D2BFA3441066:5339804)
        at |lyra|{/system/lib64/libart.so}.ExecuteMterpImpl(40255FA0-FC4E-1935-A58C-D2BFA3441066:5482008)
        at |lyra|{/system/lib64/libart.so}.(40255FA0-FC4E-1935-A58C-D2BFA3441066:2297016)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadERKNS_20CodeItemDataAccessorEPNS_11ShadowFrameEPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2320300)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2453400)
        at |lyra|{/system/lib64/libart.so}.MterpInvokeDirect(40255FA0-FC4E-1935-A58C-D2BFA3441066:5344732)
        at |lyra|{/system/lib64/libart.so}.ExecuteMterpImpl(40255FA0-FC4E-1935-A58C-D2BFA3441066:5482264)
        at |lyra|{/system/lib64/libart.so}.(40255FA0-FC4E-1935-A58C-D2BFA3441066:2297016)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadERKNS_20CodeItemDataAccessorEPNS_11ShadowFrameEPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2320300)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2453400)
        at |lyra|{/system/lib64/libart.so}.MterpInvokeInterface(40255FA0-FC4E-1935-A58C-D2BFA3441066:5343768)
        at |lyra|{/system/lib64/libart.so}.ExecuteMterpImpl(40255FA0-FC4E-1935-A58C-D2BFA3441066:5482520)
2023-09-12 16:21:07.826 20622-21085/com.facebook.orca E/AndroidRuntime:     at |lyra|{/system/lib64/libart.so}.(40255FA0-FC4E-1935-A58C-D2BFA3441066:2297016)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadERKNS_20CodeItemDataAccessorEPNS_11ShadowFrameEPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2320300)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2453400)
        at |lyra|{/system/lib64/libart.so}.MterpInvokeInterface(40255FA0-FC4E-1935-A58C-D2BFA3441066:5343768)
        at |lyra|{/system/lib64/libart.so}.ExecuteMterpImpl(40255FA0-FC4E-1935-A58C-D2BFA3441066:5482520)
        at |lyra|{/system/lib64/libart.so}.(40255FA0-FC4E-1935-A58C-D2BFA3441066:2297016)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadERKNS_20CodeItemDataAccessorEPNS_11ShadowFrameEPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2320300)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2453400)
        at |lyra|{/system/lib64/libart.so}.MterpInvokeStatic(40255FA0-FC4E-1935-A58C-D2BFA3441066:5345184)
        at |lyra|{/system/lib64/libart.so}.ExecuteMterpImpl(40255FA0-FC4E-1935-A58C-D2BFA3441066:5482392)
        at |lyra|{/system/lib64/libart.so}.(40255FA0-FC4E-1935-A58C-D2BFA3441066:2297016)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadERKNS_20CodeItemDataAccessorEPNS_11ShadowFrameEPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2320300)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2453400)
        at |lyra|{/system/lib64/libart.so}.MterpInvokeVirtual(40255FA0-FC4E-1935-A58C-D2BFA3441066:5339804)
        at |lyra|{/system/lib64/libart.so}.ExecuteMterpImpl(40255FA0-FC4E-1935-A58C-D2BFA3441066:5482008)
        at |lyra|{/system/lib64/libart.so}.(40255FA0-FC4E-1935-A58C-D2BFA3441066:2297016)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadERKNS_20CodeItemDataAccessorEPNS_11ShadowFrameEPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2320300)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2453400)
        at |lyra|{/system/lib64/libart.so}.MterpInvokeStatic(40255FA0-FC4E-1935-A58C-D2BFA3441066:5345184)
        at |lyra|{/system/lib64/libart.so}.ExecuteMterpImpl(40255FA0-FC4E-1935-A58C-D2BFA3441066:5482392)
        at |lyra|{/system/lib64/libart.so}.(40255FA0-FC4E-1935-A58C-D2BFA3441066:2297016)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter33ArtInterpreterToInterpreterBridgeEPNS_6ThreadERKNS_20CodeItemDataAccessorEPNS_11ShadowFrameEPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2320300)
        at |lyra|{/system/lib64/libart.so}._ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE(40255FA0-FC4E-1935-A58C-D2BFA3441066:2453400)
        at |lyra|{/system/lib64/libart.so}.MterpInvokeSuper(40255FA0-FC4E-1935-A58C-D2BFA3441066:5341492)
        at |lyra|{/system/lib64/libart.so}.ExecuteMterpImpl(40255FA0-FC4E-1935-A58C-D2BFA3441066:5482136)
        at |lyra|{/system/lib64/libart.so}.(40255FA0-FC4E-1935-A58C-D2BFA3441066:2297016)
        at |lyra|{/system/lib64/libart.so}.artQuickToInterpreterBridge(40255FA0-FC4E-1935-A58C-D2BFA3441066:5257868)
        at |lyra|{/system/lib64/libart.so}.(40255FA0-FC4E-1935-A58C-D2BFA3441066:5574912)
        at |lyra|{/system/lib64/libart.so}.(40255FA0-FC4E-1935-A58C-D2BFA3441066:5537676)
        at |lyra|{/system/lib64/libart.so}._ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc(40255FA0-FC4E-1935-A58C-D2BFA3441066:709128)
20622-21085/com.facebook.orca E/AndroidRuntime:     at |lyra|{/system/lib64/libart.so}.(40255FA0-FC4E-1935-A58C-D2BFA3441066:4505560)
        at |lyra|{/system/lib64/libart.so}._ZN3art35InvokeVirtualOrInterfaceWithJValuesERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDP6jvalue(40255FA0-FC4E-1935-A58C-D2BFA3441066:4509844)
        at |lyra|{/system/lib64/libart.so}._ZN3art6Thread14CreateCallbackEPv(40255FA0-FC4E-1935-A58C-D2BFA3441066:4687496)
        at |lyra|{/system/lib64/libc.so}.(E9EE2633-B518-1DEF-BB5D-558CA672E8E5:537996)
        at |lyra|{/system/lib64/libc.so}.(E9EE2633-B518-1DEF-BB5D-558CA672E8E5:147936)
        at com.facebook.tigon.tigonliger.TigonLigerService.onEndpointChangedNative(Native Method)
        at com.facebook.tigon.tigonliger.TigonLigerService.lambda$registerListeners$2$com-facebook-tigon-tigonliger-TigonLigerService(:0)
        at X.2Y2.A00(:31)
        at X.2Y2.A8B(:8)
        at X.2CD.run(:243)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at X.17k.run(:0)

**Comment by ron4999** [comment]
Have you fixed it yet?
