### ISSUE TITLE
instagram error

### ISSUE THREAD

**Issue by hjf900202** [FSpaceCore/SpaceCore#68]
2023-10-10 18:29:03.274 17544-17544/com.instagram.android E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.instagram.android, PID: 17544
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.instagram.android/com.instagram.mainactivity.LauncherActivity}: java.lang.NullPointerException: Must call setInstance() first
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3876)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4018)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:111)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2474)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:240)
        at android.os.Looper.loop(Looper.java:351)
        at android.app.ActivityThread.main(ActivityThread.java:8422)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
     Caused by: java.lang.NullPointerException: Must call setInstance() first
        at X.151.A07(:9)
        at X.26R.<init>(:7)
        at com.instagram.base.activity.IgFragmentActivity.attachBaseContext(:6)
        at android.app.Activity.attach(Activity.java:8302)

**Comment by ron4999** [comment]
Have you fixed it yet?
